language: python
python:
  - "2.6"
  - "2.7"
script: ./example/manage.py test authority
env:
  - TRAVIS_DJANGO_VERSION=1.3
  - TRAVIS_DJANGO_VERSION=1.4
  - TRAVIS_DJANGO_VERSION=1.5
install:
  - pip install django==$TRAVIS_DJANGO_VERSION --use-mirrors
notifications:
  email:
    - jason.louard.ward@gmail.com
